### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by ghost** [dermike/electron-slide-beacon#17]
Steps to reproduce:
1. Clone repo
2. `npm run rebuild`
3. `npm run electron`

Environment details below.

```
Unexpected result while probing for avahi: TypeError: argument 4 must be a string (name)
    at TypeError (native)
    at supportsInterfaceIndexLocalOnly (/Users/jhabdas/Developer/electron-slide-beacon/node_modules/mdns/lib/avahi.js:17:12)
    at Object.<anonymous> (/Users/jhabdas/Developer/electron-slide-beacon/node_modules/mdns/lib/avahi.js:32:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
App threw an error during load
Error: DNSServiceRef is not initialized
    at Error (native)
    at supportsInterfaceIndexLocalOnly (/Users/jhabdas/Developer/electron-slide-beacon/node_modules/mdns/lib/avahi.js:28:10)
    at Object.<anonymous> (/Users/jhabdas/Developer/electron-slide-beacon/node_modules/mdns/lib/avahi.js:32:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
```

xcode-select version 2343 (if you need something else, lmk - the tools are installed)
npm 3.9.0
node v6.2.0

**Comment by dermike** [comment]
Thanks for the report!
This is most likely an issue with the mdns module, which if I have to guess has something to do with your node version. This project was developed with the LTS-version of node.

If you just need the functionality of this app you can download the pre-built binary:
https://github.com/dermike/electron-slide-beacon/releases/download/0.3.2/PhysicalWebBroadcast.zip

Or if you don't need the mdns support, you should be able to just comment out the  `const mdns = require('mdns');` in main.js

Will investigate more when I can!

**Comment by dermike** [comment]
According to https://github.com/electron-userland/electron-prebuilt/issues/144 it looks like it's got something to do with electron-prebuilt. See that issue for fix in the meantime. 

Either that or use LTS-version of node (currently 4.4.7)

**Comment by ghost** [comment]
Thanks for the quick turnaround.
